# Activate dev profile
spring.profiles.active=dev
server.port=8081
# MongoDB configuration for dev profile
spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/your_database_name?authSource=admin



# OAuth2 configuration for dev profile (Google OAuth)
# spring.security.oauth2.client.registration.google.client-id=Your_client_id
# spring.security.oauth2.client.registration.google.client-secret=Your_secret_key
#spring.security.oauth2.client.registration.google.scope=openid, profile, email
# spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
# spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
# spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
# spring.security.oauth2.client.provider.google.user-name-attribute=sub

# Flak service URL
flask.meal.api.url=http://localhost:5000/generate

# application.properties
jwt.secret=YourSuperSecretKeyOfAtLeast32Chars
jwt.expiration=86400000 


